### ISSUE TITLE
Can't run on MSI GS66

### ISSUE THREAD

**Issue by asheghi** [YoCodingMonster/OpenFreezeCenter#155]
Device: Stealth GS66 12UGS
Opeation System: Ubuntu 22.04
Desktop: gone 42.5 (X11)

reproduce:
1. cloned project
2. installed dependencies with `sudo ./install-deps.sh`
3. `sudo ./at_startup.sh` exit without any output

Here's the output for `sudo python3 indicator.py`:
```bash
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Traceback (most recent call last):
  File "/home/bahman/OpenFreezeCenter/indicator.py", line 39, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

**Comment by jsw08** [comment]
Do you mean gnome instead of gone as desktop environment? If so, you might need to install an extension for appindicator support. [Here's](https://extensions.gnome.org/extension/615/appindicator-support/) the one that I recommend.

**Comment by asheghi** [comment]
Yes, it's Gnome, 

I already have the app indicator extension enabled and I can see indicators from other applications, I've also installed the extension you mentioned but it still throws the same error.

**Comment by jsw08** [comment]
The only other thing I could think of is that appindicator3 is not installed. 
```sh
sudo apt install gir1.2-appindicator3-0.1
```
I can not help you any further than this. Sorry and good luck!
