### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/OpenFreezeCenter/config.py'

### ISSUE THREAD

**Issue by empierre** [YoCodingMonster/OpenFreezeCenter#182]
Hello,

  ran it the first time, but since it required reboot I stopped it.
Now after a reboot of my own I have this:

 python3 OFC.py
Traceback (most recent call last):
  File "/root/OpenFreezeCenter/OFC.py", line 59, in <module>
    CONFIG_FILE = open(PATH_TO_CONFIG, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/root/OpenFreezeCenter/config.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/OpenFreezeCenter/OFC.py", line 64, in <module>
    LINE_NO = "PROFILE = 1\nAUTO_SPEED = [["+str(ECT.read(0x72, 1))+", "+str(ECT.read(0x73, 1))+", "+str(ECT.read(0x74, 1))+", "+str(ECT.read(0x75, 1))+", "+str(ECT.read(0x76, 1))+", "+str(ECT.read(0x77, 1))+", "+str(ECT.read(0x78, 1))+"], ["+str(ECT.read(0x8a, 1))+", "+str(ECT.read(0x8b, 1))+", "+str(ECT.read(0x8c, 1))+", "+str(ECT.read(0x8d, 1))+", "+str(ECT.read(0x8e, 1))+", "+str(ECT.read(0x8f, 1))+", "+str(ECT.read(0x90, 1))+"]]"
  File "/usr/local/lib/python3.10/dist-packages/ECTweaker.py", line 39, in read
    with open(EC_IO_FILE,'r+b') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/OpenFreezeCenter/OFC.py", line 76, in <module>
    import config
ModuleNotFoundError: No module named 'config'

**Comment by VMDat** [comment]
for "FileNotFoundError: [Errno 2] No such file or directory: '/root/OpenFreezeCenter/config.py'

=> "create config.py 
then paste the following text into the file (worked for me):

PROFILE = 2
AUTO_SPEED = [[0, 40, 48, 56, 64, 72, 80], [0, 48, 56, 64, 72, 79, 86]]
ADV_SPEED = [[0, 40, 48, 56, 64, 72, 80], [0, 48, 56, 64, 72, 79, 86]]
BASIC_OFFSET = 0
CPU = 1
AUTO_ADV_VALUES = [212, 13, 141]
COOLER_BOOSTER_OFF_ON_VALUES = [152, 2, 130]
CPU_GPU_FAN_SPEED_ADDRESS = [[114, 115, 116, 117, 118, 119, 120], [138, 139, 140, 141, 142, 143, 144]]
CPU_GPU_TEMP_ADDRESS = [104, 128]
CPU_GPU_RPM_ADDRESS = [200, 202]
BATTERY_THRESHOLD_VALUE = 100

=> retry
