### ISSUE TITLE
Exception related to GTK when running on Arch Linux

### ISSUE THREAD

**Issue by Sonickyle27** [YoCodingMonster/OpenFreezeCenter#23]
When attempting to run the `indicator.py` script on a up-to-date Arch Linux installation, this exception occurs:

```
/home/treasure/Documents/git/OpenFreezeCenter/./indicator.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository  import Gtk as gtk
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 137, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 257, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 109, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/treasure/Documents/git/OpenFreezeCenter/./indicator.py", line 9, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 139, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
```

**Comment by YoCodingMonster** [comment]
Add

```
import gi.repository
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
```

After `from gi.repository import AppIndicator3 as appindicator`

In Indicator.py file. Then run

**Comment by Sonickyle27** [comment]
Thanks, I tried doing that so now the imports look like

```
import signal
import os
import subprocess
import webbrowser
import fileinput
import gi.repository
from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
import gi.repository
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
```

But this makes no difference and still gives me the following error:

```
/home/treasure/Documents/git/OpenFreezeCenter/./indicator.py:9: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 137, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 257, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 109, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/treasure/Documents/git/OpenFreezeCenter/./indicator.py", line 10, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 139, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
```

**Comment by YoCodingMonster** [comment]
gi.require
lines goes before importing them not after

```
import gi.repository
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
```
all together not saperately

**Comment by Sonickyle27** [comment]
Thanks, I no longer get that error message.
